ACCEPT = 'Quiero'
DONT_ACCEPT = 'No Quiero'
FINAL_ANSWER = [ACCEPT, DONT_ACCEPT]
ENVIDO = 'Envido'
REAL_ENVIDO = 'Real Envido'
FALTA_ENVIDO = 'Falta Envido'
TRUCO = 'Truco'
RE_TRUCO = 'Re Truco'
VALE_CUATRO = 'Vale Cuatro'
ABANDON = "Mazo"